# Route/template registries for the generated documentation library scaffolds.
# Each entry is (endpoint, url_path, template_file, title).
# LIBRARY1 pages are public. LIBRARY2 pages require an authenticated customer
# (admin_required) - this is the Trust Center's "authenticated customer" tier.
# LIBRARY3 pages are LBS-internal; they are intentionally not linked from any
# public or customer-facing page and are not real access control (see app.py).

LIBRARY1 = [
    ("cookie_policy", "/cookie-policy", "cookie_policy.html", "Cookie Policy"),
    ("accessibility_statement", "/accessibility", "accessibility_statement.html", "Accessibility Statement"),
    ("responsible_disclosure", "/responsible-disclosure", "responsible_disclosure.html", "Responsible Disclosure Policy"),
    ("copyright_policy", "/copyright-policy", "copyright_policy.html", "Copyright Policy"),
    ("trademark_guidelines", "/trademark-guidelines", "trademark_guidelines.html", "Trademark Usage Guidelines"),
    ("faq_page", "/faq", "faq_page.html", "Frequently Asked Questions"),
    ("product_overview", "/product-overview", "product_overview.html", "Product Overview"),
    ("feature_overview", "/features", "feature_overview.html", "Feature Overview"),
    ("pricing_explanation", "/pricing-explained", "pricing_explanation.html", "Pricing Explanation"),
    ("security_overview", "/security-overview", "security_overview.html", "Security Overview"),
    ("compliance_overview", "/compliance-overview", "compliance_overview.html", "Compliance Overview"),
    ("data_protection_overview", "/data-protection-overview", "data_protection_overview.html", "Data Protection Overview"),
    ("subprocessor_overview", "/subprocessors", "subprocessor_overview.html", "Subprocessor Overview"),
    ("system_requirements", "/system-requirements", "system_requirements.html", "System Requirements"),
    ("browser_support", "/browser-support", "browser_support.html", "Browser Support"),
    ("release_notes", "/release-notes", "release_notes.html", "Release Notes"),
    ("api_overview", "/api-overview", "api_overview.html", "API Overview"),
    ("status_page_info", "/status", "status_page_info.html", "Status Page Information"),
    ("support_center", "/support", "support_center.html", "Support Center"),
    ("onboarding_guide", "/onboarding-guide", "onboarding_guide.html", "Customer Onboarding Guide"),
    ("user_guide", "/user-guide", "user_guide.html", "User Guide"),
    ("admin_guide_customer", "/admin-guide", "admin_guide_customer.html", "Administrator Guide"),
    ("password_policy_page", "/password-policy", "password_policy_page.html", "Password Policy"),
    ("password_reset_guide_page", "/password-reset-guide", "password_reset_guide_page.html", "Password Reset Guide"),
    ("mfa_guide", "/mfa-guide", "mfa_guide.html", "Multi-Factor Authentication Guide"),
    ("billing_faq", "/billing-faq", "billing_faq.html", "Billing FAQ"),
    ("subscription_faq", "/subscription-faq", "subscription_faq.html", "Subscription FAQ"),
    ("cancellation_policy", "/cancellation-policy", "cancellation_policy.html", "Cancellation Policy"),
    ("refund_policy", "/refund-policy", "refund_policy.html", "Refund Policy"),
    ("availability_commitment", "/availability-commitment", "availability_commitment.html", "Availability Commitment"),
    ("training_resources", "/training-resources", "training_resources.html", "Training Resources"),
    ("video_documentation", "/video-docs", "video_documentation.html", "Video Documentation"),
    ("knowledge_base", "/knowledge-base", "knowledge_base.html", "Knowledge Base"),
]

# (endpoint, url_slug, template_file, title) - url is /trust-center/<url_slug>
LIBRARY2 = [
    ("tc_enterprise_security_overview", "enterprise-security-overview", "tc_enterprise_security_overview.html", "Enterprise Security Overview"),
    ("tc_security_controls_summary", "security-controls-summary", "tc_security_controls_summary.html", "Security Controls Summary"),
    ("tc_encryption_standards", "encryption-standards", "tc_encryption_standards.html", "Encryption Standards"),
    ("tc_key_management_overview", "key-management-overview", "tc_key_management_overview.html", "Key Management Overview"),
    ("tc_identity_management_overview", "identity-management-overview", "tc_identity_management_overview.html", "Identity Management Overview"),
    ("tc_access_control_overview", "access-control-overview", "tc_access_control_overview.html", "Access Control Overview"),
    ("tc_infrastructure_overview", "infrastructure-overview", "tc_infrastructure_overview.html", "Infrastructure Overview"),
    ("tc_business_continuity_summary", "business-continuity-summary", "tc_business_continuity_summary.html", "Business Continuity Summary"),
    ("tc_disaster_recovery_summary", "disaster-recovery-summary", "tc_disaster_recovery_summary.html", "Disaster Recovery Summary"),
    ("tc_security_incident_notification", "security-incident-notification-process", "tc_security_incident_notification.html", "Security Incident Notification Process"),
    ("tc_privacy_compliance_guide", "privacy-compliance-guide", "tc_privacy_compliance_guide.html", "Privacy Compliance Guide"),
    ("tc_gdpr_statement", "gdpr-statement", "tc_gdpr_statement.html", "GDPR Statement"),
    ("tc_ccpa_statement", "ccpa-statement", "tc_ccpa_statement.html", "CCPA Statement"),
    ("tc_data_retention_summary", "data-retention-summary", "tc_data_retention_summary.html", "Data Retention Summary"),
    ("tc_data_deletion_process", "data-deletion-process", "tc_data_deletion_process.html", "Data Deletion Process"),
    ("tc_backup_overview", "backup-overview", "tc_backup_overview.html", "Backup Overview"),
    ("tc_audit_logging_overview", "audit-logging-overview", "tc_audit_logging_overview.html", "Audit Logging Overview"),
    ("tc_authentication_overview", "authentication-overview", "tc_authentication_overview.html", "Authentication Overview"),
    ("tc_authorization_overview", "authorization-overview", "tc_authorization_overview.html", "Authorization Overview"),
    ("tc_tenant_isolation_overview", "tenant-isolation-overview", "tc_tenant_isolation_overview.html", "Tenant Isolation Overview"),
    ("tc_secure_development_lifecycle", "secure-development-lifecycle", "tc_secure_development_lifecycle.html", "Secure Development Lifecycle"),
    ("tc_vulnerability_management_summary", "vulnerability-management-summary", "tc_vulnerability_management_summary.html", "Vulnerability Management Summary"),
    ("tc_patch_management_summary", "patch-management-summary", "tc_patch_management_summary.html", "Patch Management Summary"),
    ("tc_penetration_testing_summary", "penetration-testing-summary", "tc_penetration_testing_summary.html", "Penetration Testing Summary"),
    ("tc_responsible_ai_statement", "responsible-ai-statement", "tc_responsible_ai_statement.html", "Responsible AI Statement"),
    ("tc_risk_management_summary", "risk-management-summary", "tc_risk_management_summary.html", "Risk Management Summary"),
    ("tc_vendor_management_overview", "vendor-management-overview", "tc_vendor_management_overview.html", "Vendor Management Overview"),
    ("tc_compliance_roadmap", "compliance-roadmap", "tc_compliance_roadmap.html", "Compliance Roadmap"),
    ("tc_security_faq", "security-faq", "tc_security_faq.html", "Security FAQ"),
    ("tc_soc2_readiness_statement", "soc2-readiness-statement", "tc_soc2_readiness_statement.html", "SOC 2 Readiness Statement"),
    ("tc_iso27001_roadmap", "iso27001-roadmap", "tc_iso27001_roadmap.html", "ISO 27001 Roadmap"),
    ("tc_security_contact_information", "security-contact-information", "tc_security_contact_information.html", "Security Contact Information"),
    ("tc_subprocessor_list", "subprocessor-list", "tc_subprocessor_list.html", "Subprocessor List"),
    ("tc_data_residency_statement", "data-residency-statement", "tc_data_residency_statement.html", "Data Residency Statement"),
    ("tc_compliance_matrix", "compliance-matrix", "tc_compliance_matrix.html", "Compliance Matrix"),
    ("tc_customer_security_questionnaire", "customer-security-questionnaire", "tc_customer_security_questionnaire.html", "Customer Security Questionnaire"),
]

# (endpoint, url_slug, template_file, title, section) - url is /internal/<url_slug>
# section groups them on the internal index page.
LIBRARY3 = [
    # Product Documentation
    ("int_prs", "product-requirements-specification", "int_prs.html", "Product Requirements Specification", "Product Documentation"),
    ("int_engineering_standards", "engineering-standards", "int_engineering_standards.html", "Engineering Standards", "Product Documentation"),
    ("int_architecture_standards", "architecture-standards", "int_architecture_standards.html", "Architecture Standards", "Product Documentation"),
    ("int_coding_standards", "coding-standards", "int_coding_standards.html", "Coding Standards", "Product Documentation"),
    ("int_database_standards", "database-standards", "int_database_standards.html", "Database Standards", "Product Documentation"),
    ("int_api_standards", "api-standards", "int_api_standards.html", "API Standards", "Product Documentation"),
    ("int_ui_standards", "ui-standards", "int_ui_standards.html", "UI Standards", "Product Documentation"),
    ("int_ux_standards", "ux-standards", "int_ux_standards.html", "UX Standards", "Product Documentation"),
    ("int_design_system", "design-system", "int_design_system.html", "Design System", "Product Documentation"),
    ("int_style_guide", "style-guide", "int_style_guide.html", "Style Guide", "Product Documentation"),

    # Engineering
    ("int_system_architecture", "system-architecture", "int_system_architecture.html", "System Architecture", "Engineering"),
    ("int_microservice_architecture", "microservice-architecture", "int_microservice_architecture.html", "Microservice Architecture", "Engineering"),
    ("int_database_schema", "database-schema", "int_database_schema.html", "Database Schema", "Engineering"),
    ("int_er_diagrams", "er-diagrams", "int_er_diagrams.html", "ER Diagrams", "Engineering"),
    ("int_sequence_diagrams", "sequence-diagrams", "int_sequence_diagrams.html", "Sequence Diagrams", "Engineering"),
    ("int_api_specifications", "api-specifications", "int_api_specifications.html", "API Specifications", "Engineering"),
    ("int_deployment_guide", "deployment-guide", "int_deployment_guide.html", "Deployment Guide", "Engineering"),
    ("int_infrastructure_guide", "infrastructure-guide", "int_infrastructure_guide.html", "Infrastructure Guide", "Engineering"),
    ("int_environment_configuration", "environment-configuration", "int_environment_configuration.html", "Environment Configuration", "Engineering"),
    ("int_devops_manual", "devops-manual", "int_devops_manual.html", "DevOps Manual", "Engineering"),
    ("int_cicd_guide", "cicd-guide", "int_cicd_guide.html", "CI/CD Guide", "Engineering"),
    ("int_release_management", "release-management", "int_release_management.html", "Release Management", "Engineering"),
    ("int_monitoring_guide", "monitoring-guide", "int_monitoring_guide.html", "Monitoring Guide", "Engineering"),
    ("int_logging_standards", "logging-standards", "int_logging_standards.html", "Logging Standards", "Engineering"),
    ("int_observability_guide", "observability-guide", "int_observability_guide.html", "Observability Guide", "Engineering"),
    ("int_performance_standards", "performance-standards", "int_performance_standards.html", "Performance Standards", "Engineering"),
    ("int_scaling_strategy", "scaling-strategy", "int_scaling_strategy.html", "Scaling Strategy", "Engineering"),
    ("int_caching_strategy", "caching-strategy", "int_caching_strategy.html", "Caching Strategy", "Engineering"),
    ("int_queue_architecture", "queue-architecture", "int_queue_architecture.html", "Queue Architecture", "Engineering"),
    ("int_backup_architecture", "backup-architecture", "int_backup_architecture.html", "Backup Architecture", "Engineering"),
    ("int_iac_standards", "infrastructure-as-code-standards", "int_iac_standards.html", "Infrastructure as Code Standards", "Engineering"),

    # Security
    ("int_security_policy_internal", "security-policy-internal", "int_security_policy_internal.html", "Security Policy (Internal)", "Security"),
    ("int_secure_coding_standards", "secure-coding-standards", "int_secure_coding_standards.html", "Secure Coding Standards", "Security"),
    ("int_iam_standard", "identity-access-management-standard", "int_iam_standard.html", "Identity & Access Management Standard", "Security"),
    ("int_key_management_standard", "key-management-standard", "int_key_management_standard.html", "Key Management Standard", "Security"),
    ("int_vulnerability_management_procedure", "vulnerability-management-procedure", "int_vulnerability_management_procedure.html", "Vulnerability Management Procedure", "Security"),
    ("int_patch_management_procedure", "patch-management-procedure", "int_patch_management_procedure.html", "Patch Management Procedure", "Security"),
    ("int_threat_modeling_standard", "threat-modeling-standard", "int_threat_modeling_standard.html", "Threat Modeling Standard", "Security"),
    ("int_risk_assessment_procedure", "risk-assessment-procedure", "int_risk_assessment_procedure.html", "Risk Assessment Procedure", "Security"),
    ("int_vendor_risk_assessment", "vendor-risk-assessment", "int_vendor_risk_assessment.html", "Vendor Risk Assessment", "Security"),
    ("int_access_review_procedure", "access-review-procedure", "int_access_review_procedure.html", "Access Review Procedure", "Security"),
    ("int_security_monitoring_runbook", "security-monitoring-runbook", "int_security_monitoring_runbook.html", "Security Monitoring Runbook", "Security"),
    ("int_soc2_readiness_plan", "soc2-readiness-plan", "int_soc2_readiness_plan.html", "SOC 2 Readiness Plan", "Security"),
    ("int_internal_audit_guide", "internal-audit-guide", "int_internal_audit_guide.html", "Internal Audit Guide", "Security"),
    ("int_penetration_testing_procedure", "penetration-testing-procedure", "int_penetration_testing_procedure.html", "Penetration Testing Procedure", "Security"),
    ("int_security_awareness_program", "security-awareness-program", "int_security_awareness_program.html", "Security Awareness Program", "Security"),

    # Operations
    ("int_operational_runbooks", "operational-runbooks", "int_operational_runbooks.html", "Operational Runbooks", "Operations"),
    ("int_administrator_runbooks", "administrator-runbooks", "int_administrator_runbooks.html", "Administrator Runbooks", "Operations"),
    ("int_payroll_processing_manual", "payroll-processing-manual", "int_payroll_processing_manual.html", "Payroll Processing Manual", "Operations"),
    ("int_support_manual", "support-manual", "int_support_manual.html", "Support Manual", "Operations"),
    ("int_customer_success_manual", "customer-success-manual", "int_customer_success_manual.html", "Customer Success Manual", "Operations"),
    ("int_escalation_procedures", "escalation-procedures", "int_escalation_procedures.html", "Escalation Procedures", "Operations"),
    ("int_change_management_procedure", "change-management-procedure", "int_change_management_procedure.html", "Change Management Procedure", "Operations"),
    ("int_configuration_management", "configuration-management", "int_configuration_management.html", "Configuration Management", "Operations"),
    ("int_release_checklist", "release-checklist", "int_release_checklist.html", "Release Checklist", "Operations"),
    ("int_deployment_checklist", "deployment-checklist", "int_deployment_checklist.html", "Deployment Checklist", "Operations"),
    ("int_incident_checklist", "incident-checklist", "int_incident_checklist.html", "Incident Checklist", "Operations"),
    ("int_maintenance_procedures", "maintenance-procedures", "int_maintenance_procedures.html", "Maintenance Procedures", "Operations"),
    ("int_backup_verification", "backup-verification", "int_backup_verification.html", "Backup Verification", "Operations"),
    ("int_recovery_verification", "recovery-verification", "int_recovery_verification.html", "Recovery Verification", "Operations"),
    ("int_monitoring_sop", "monitoring-sop", "int_monitoring_sop.html", "Monitoring SOP", "Operations"),
    ("int_employee_onboarding_guide", "employee-onboarding-guide", "int_employee_onboarding_guide.html", "Employee Onboarding Guide", "Operations"),
    ("int_offboarding_procedure", "offboarding-procedure", "int_offboarding_procedure.html", "Offboarding Procedure", "Operations"),
    ("int_vendor_management_guide", "vendor-management-guide", "int_vendor_management_guide.html", "Vendor Management Guide", "Operations"),
    ("int_disaster_activation_checklist", "disaster-activation-checklist", "int_disaster_activation_checklist.html", "Disaster Activation Checklist", "Operations"),
    ("int_bc_activation_checklist", "business-continuity-activation-checklist", "int_bc_activation_checklist.html", "Business Continuity Activation Checklist", "Operations"),

    # Quality Assurance
    ("int_qa_strategy", "qa-strategy", "int_qa_strategy.html", "QA Strategy", "Quality Assurance"),
    ("int_test_strategy", "test-strategy", "int_test_strategy.html", "Test Strategy", "Quality Assurance"),
    ("int_automation_strategy", "automation-strategy", "int_automation_strategy.html", "Automation Strategy", "Quality Assurance"),
    ("int_unit_testing_standards", "unit-testing-standards", "int_unit_testing_standards.html", "Unit Testing Standards", "Quality Assurance"),
    ("int_integration_testing_standards", "integration-testing-standards", "int_integration_testing_standards.html", "Integration Testing Standards", "Quality Assurance"),
    ("int_performance_testing", "performance-testing", "int_performance_testing.html", "Performance Testing", "Quality Assurance"),
    ("int_accessibility_testing", "accessibility-testing", "int_accessibility_testing.html", "Accessibility Testing", "Quality Assurance"),
    ("int_regression_testing", "regression-testing", "int_regression_testing.html", "Regression Testing", "Quality Assurance"),
    ("int_uat_procedures", "uat-procedures", "int_uat_procedures.html", "UAT Procedures", "Quality Assurance"),
    ("int_bug_lifecycle", "bug-lifecycle", "int_bug_lifecycle.html", "Bug Lifecycle", "Quality Assurance"),
    ("int_definition_of_ready", "definition-of-ready", "int_definition_of_ready.html", "Definition of Ready", "Quality Assurance"),
    ("int_definition_of_done", "definition-of-done", "int_definition_of_done.html", "Definition of Done", "Quality Assurance"),
    ("int_release_acceptance_criteria", "release-acceptance-criteria", "int_release_acceptance_criteria.html", "Release Acceptance Criteria", "Quality Assurance"),

    # Product Management
    ("int_roadmap", "roadmap", "int_roadmap.html", "Roadmap", "Product Management"),
    ("int_release_planning", "release-planning", "int_release_planning.html", "Release Planning", "Product Management"),
    ("int_feature_lifecycle", "feature-lifecycle", "int_feature_lifecycle.html", "Feature Lifecycle", "Product Management"),
    ("int_requirements_template", "requirements-template", "int_requirements_template.html", "Requirements Template", "Product Management"),
    ("int_user_story_standards", "user-story-standards", "int_user_story_standards.html", "User Story Standards", "Product Management"),
    ("int_acceptance_criteria_standards", "acceptance-criteria-standards", "int_acceptance_criteria_standards.html", "Acceptance Criteria Standards", "Product Management"),
    ("int_product_metrics", "product-metrics", "int_product_metrics.html", "Product Metrics", "Product Management"),
    ("int_kpis", "kpis", "int_kpis.html", "KPIs", "Product Management"),
    ("int_okrs", "okrs", "int_okrs.html", "OKRs", "Product Management"),
    ("int_sprint_planning_guide", "sprint-planning-guide", "int_sprint_planning_guide.html", "Sprint Planning Guide", "Product Management"),
    ("int_backlog_grooming_guide", "backlog-grooming-guide", "int_backlog_grooming_guide.html", "Backlog Grooming Guide", "Product Management"),
    ("int_product_governance", "product-governance", "int_product_governance.html", "Product Governance", "Product Management"),
    ("int_customer_feedback_process", "customer-feedback-process", "int_customer_feedback_process.html", "Customer Feedback Process", "Product Management"),
    ("int_feature_request_process", "feature-request-process", "int_feature_request_process.html", "Feature Request Process", "Product Management"),
]

# The 4 real internal documents, built from verbatim customer-supplied text.
LIBRARY3_REAL = [
    ("int_bcp", "business-continuity-plan", "int_bcp.html", "Business Continuity Plan (BCP)"),
    ("int_drp", "disaster-recovery-plan", "int_drp.html", "Disaster Recovery Plan (DRP)"),
    ("int_irp", "incident-response-plan", "int_irp.html", "Incident Response Plan (IRP)"),
    ("int_tds", "technical-design-specification", "int_tds.html", "Technical Design Specification (TDS)"),
]
